apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: app


resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

images:
- name: amralaayassen/tradebyte-challenge
  newName: amralaayassen/tradebyte-challenge
  newTag: 0.0.1
