name: Tradebyte CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-app:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python tests/test.py
  build-push-docker:
    name: Build & Push Docker
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker
        run: docker build -t ${{secrets.CONTAINER_REGISTRY}}/tradebyte-challenge:${{github.sha}} .

      - name: Docker Push
        run: docker push ${{secrets.CONTAINER_REGISTRY}}/tradebyte-challenge:${{github.sha}}

        