name: Tradebyte CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-app:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python tests/test.py

  build-push-docker:
    name: Build & Push Docker
    runs-on: ubuntu-latest
    environment: STAGING
    needs: build-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker 
        run: docker build -t ${{secrets.CONTAINER_REGISTRY}}/tradebyte-challenge:${{github.sha}} ./$DIR
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{secrets.CONTAINER_REGISTRY}}/tradebyte-challenge:${{github.sha}}'
          format: 'sarif'
          output: 'trivy-scan-result.sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-scan-result.sarif'

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: trivy-scan-result 
          path: trivy-scan-result.sarif


      - name: Docker Push
        run: docker push ${{secrets.CONTAINER_REGISTRY}}/tradebyte-challenge:${{github.sha}}

        